CREATE TABLE `oedipus_frame_trees` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`parent_id` INT UNSIGNED NOT NULL ,
`lft` INT UNSIGNED NOT NULL ,
`rgt` INT UNSIGNED NOT NULL ,
`scene_id` INT UNSIGNED NOT NULL ,
`frame_id` INT UNSIGNED NOT NULL
) ENGINE = MYISAM ;
